<?php

use Illuminate\Database\Seeder;

class LearningTaskTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('learningtask_template')->insert([
            [
                'title' => 'Students conduct a client interview to understand the design needs',
                'time' => 5,
                'type' => 1,
                'class_type' => 1,
                'target' => 1,
                'size' => 2,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => 'Students conduct a client interview to understand the design needs',
                'time' => 15,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 2,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => 'Students work on the information collected from the interview, 
                and select the most prominent problem needed to be addressed.',
                'time' => 10,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 2,
                'description' => 'The design brief should focus on functional request of the product',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => 'Students present their findings on user needs to the whole class',
                'time' => 5,
                'type' => 4,
                'class_type' => 1,
                'target' => 1,
                'size' => 2,
                'description' => 'The design brief should focus on functional request of the product',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => 'Students search and study existing solutions to the users needs.',
                'time' => 30,
                'type' => 5,
                'class_type' => 2,
                'target' => 1,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => 'Students brainstorm on their findings, and converge on one best/feasible solution.',
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => 'Teachers can introduce the interview technique for each group and guide their thinking',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => 'Students work out a plan/draw sketch design to construct prototype.',
                'time' => 15,
                'type' => 3,
                'class_type' => 1,
                'target' => 1,
                'size' => 3,
                'description' => 'Teachers can introduce the interview technique for each group and guide their thinking',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => 'Students receive feedback and comments from teachers and other students',
                'time' => 5,
                'type' => 6,
                'class_type' => 1,
                'target' => 1,
                'size' => 3,
                'description' => 'Teachers can introduce the interview technique for each group and guide their thinking',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => 'Students revise the design problem based on the feedback received.',
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 1,
                'size' => 3,
                'description' => 'Teachers can introduce the interview technique for each group and guide their thinking',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Group discussion to identify the factors to be evaluate 
                the prototype that fulfills users' need",
                'time' => 10,
                'type' => 2,
                'class_type' => 1,
                'target' => 1,
                'size' => 4,
                'description' => 'Teachers can use video, news clips',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students list criteria/rubric used to evaluate 
                the effectiveness of the prototype",
                'time' => 10,
                'type' => 3,
                'class_type' => 2,
                'target' => 2,
                'size' => 3,
                'description' => 'Teachers can introduce the interview technique for each group and guide their thinking',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students explores the materials",
                'time' => 60,
                'type' => 8,
                'class_type' => 2,
                'target' => 2,
                'size' => 4,
                'description' => 'Teachers can use video, news clips',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students produce an early, inexpensive, and scaled down version of the product",
                'time' => 60,
                'type' => 3,
                'class_type' => 2,
                'target' => 2,
                'size' => 3,
                'description' => 'Teachers can introduce the interview technique for each group and guide their thinking',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students receive teachers' instruction on the success criteria of the competition",
                'time' => 5,
                'type' => 5,
                'class_type' => 2,
                'target' => 2,
                'size' => 3,
                'description' => 'Teachers can use video, news clips',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students perform their product",
                'time' => 30,
                'type' => 6,
                'class_type' => 1,
                'target' => 3,
                'size' => 5,
                'description' => 'Teachers can introduce the interview technique for each group and guide their thinking',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students self/peer evaluate the performance of their products based on the rubrics.",
                'time' => 10,
                'type' => 6,
                'class_type' => 1,
                'target' => 3,
                'size' => 5,
                'description' => 'Teachers can introduce the interview technique for each group and guide their thinking',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students receive teachers' instruction on 
                conducting a client interview for the effectiveness of the product.",
                'time' => 5,
                'type' => 6,
                'class_type' => 1,
                'target' => 1,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students conduct a client interview to 
                collect the feedback from the users who try out the products",
                'time' => 15,
                'type' => 6,
                'class_type' => 1,
                'target' => 1,
                'size' => 5,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students self/peer evaluate the 
                performance of their products based on the rubrics..",
                'time' => 10,
                'type' => 6,
                'class_type' => 1,
                'target' => 1,
                'size' => 5,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students analyze the feedback from users/teachers, and search methods to optimie the product",
                'time' => 30,
                'type' => 5,
                'class_type' => 2,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students brainstorm on their findings, and converge on one best/feasible solution.",
                'time' => 10,
                'type' => 5,
                'class_type' => 1,
                'target' => 3,
                'size' => 5,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students work out a plan/draw sketch design to construct prototype",
                'time' => 15,
                'type' => 6,
                'class_type' => 1,
                'target' => 3,
                'size' => 5,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students work on the product optimization",
                'time' => 30,
                'type' => 6,
                'class_type' => 1,
                'target' => 3,
                'size' => 5,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students observe the scenario of the design problem through stimulus",
                'time' => 5,
                'type' => 1,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Based on the scenario, 
                students predict what would happen when a particular variable change.",
                'time' => 5,
                'type' => 7,
                'class_type' => 1,
                'target' => 3,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students discuss and explain what has been observed: whether and why",
                'time' => 10,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students write down the inquiry questions and shared with the whole class",
                'time' => 5,
                'type' => 3,
                'class_type' => 2,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students discuss and explain what has been observed: whether and why",
                'time' => 10,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students write down the inquiry questions and shared with the whole class",
                'time' => 5,
                'type' => 3,
                'class_type' => 2,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students search and explore new 
                relevant information about the variables of the problem",
                'time' => 30,
                'type' => 1,
                'class_type' => 2,
                'target' => 3,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Group discussion and come up with some hypothesis",
                'time' => 10,
                'type' => 2,
                'class_type' => 1,
                'target' =>2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Write down the hypothesis and
                share with the whole class",
                'time' => 5,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students receive feedback and
                comments from teachers and other students",
                'time' => 5,
                'type' => 6,
                'class_type' => 1,
                'target' => 2,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students revise the hypothesis
                based on the feedback received.",
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Group discussion to differentiate dependent/independent/control
                varibles and design instrument to measure the variables",
                'time' => 15,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 4,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students write a plan of scientific inquiry",
                'time' => 15,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 4,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students reflect on the alignmennt between hypothesis and inquiry methods,
                as well as other practical issues of the experiment design",
                'time' => 5,
                'type' => 9,
                'class_type' => 2,
                'target' => 3,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students revise and finalize the plan",
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 2,
                'size' => 4,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Group discussion to identify the factors to be monitored for 
                the successful implementation of the experiment plan",
                'time' => 10,
                'type' => 2,
                'class_type' => 2,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "List criteria/rubric used to evaluate the success of the experiment",
                'time' => 10,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Conduct the experiment, observe the phenomena and record the data",
                'time' => 20,
                'type' => 8,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Conduct self-/peer-assessment
                on the experiment procedure to identify the areas of improvement",
                'time' => 10,
                'type' => 6,
                'class_type' => 1,
                'target' => 2,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Improve the experienment design and operation",
                'time' => 10,
                'type' => 6,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Summarize and display the data in the form of spreadsheets, tables, or charts.",
                'time' => 10,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students identify causal and correlational 
                relationship of different groups of data sets.",
                'time' => 5,
                'type' => 9,
                'class_type' => 1,
                'target' => 3,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students choose valid and reliable evidences that support the claims.",
                'time' => 5,
                'type' => 9,
                'class_type' => 1,
                'target' => 3,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students apply scientific
                principles/theories to construct an explanation for the results.",
                'time' => 10,
                'type' => 9,
                'class_type' => 1,
                'target' => 3,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students write down their statements
                on the process of scientific reasoning.",
                'time' => 5,
                'type' => 9,
                'class_type' => 1,
                'target' => 3,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Conduct self-assessment on the scientific
                reasoning process (claim, evidence, reasoning )",
                'time' => 10,
                'type' => 9,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students improve the process of scientific reasoning",
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 2,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'title' => "Students construct graphical displays to illustrate the
                relationships of the variables, and present to the whole class",
                'time' => 10,
                'type' => 10,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);

        DB::table('learningtask_template_assessment')->insert([
            [
                'learningtask_id' => 1,
                'learningoutcome_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);

        DB::table('learningtask_template_resource')->insert([
            [
                'learningtask_id' => 1,
                'resource_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);

        DB::table('learningtask_template_etool')->insert([
            [
                'learningtask_id' => 1,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }
}
