<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateLearningtaskTemplate extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('learningtask_template', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('title');
            $table->bigInteger('time');
            $table->unsignedBigInteger('type');
            $table->unsignedBigInteger('class_type');
            $table->unsignedBigInteger('target');
            $table->unsignedBigInteger('size');
            $table->string('description');
            $table->smallInteger('created_by');
            $table->smallInteger('updated_by');
            $table->boolean('is_deleted');
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();

            $table->foreign('type')->references('id')->on('learningTasktypeOpts');
            $table->foreign('class_type')->references('id')->on('classTargetOpts');
            $table->foreign('target')->references('id')->on('classTargetOpts');
            $table->foreign('size')->references('id')->on('classSizeOpts');
        });

        DB::table('learningtask_template')->insert([
            [
                'id' => 1,
                'title' => 'Students observe the scenario of the design problem through stimulus',
                'time' => 5,
                'type' => 1,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 2,
                'title' => 'Students conduct a client interview to understand the design needs',
                'time' => 15,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 3,
                'title' => 'Students work on the information collected from the interview, and select the most prominent problem needed to be addressed.',
                'time' => 10,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 4,
                'title' => 'Students present their findings on user needs to the whole class',
                'time' => 5,
                'type' => 4,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 5,
                'title' => 'Students observe the scenario of the design problem through stimulus',
                'time' => 5,
                'type' => 1,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 6,
                'title' => 'Students discuss the needs of users',
                'time' => 15,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 7,
                'title' => 'Students work on indentifying the most prominent problem needed to be addressed.',
                'time' => 5,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 8,
                'title' => 'Students present their findings on user needs to the whole class',
                'time' => 5,
                'type' => 4,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 9,
                'title' => 'Students search and study existing solutions to the users needs.',
                'time' => 30,
                'type' => 5,
                'class_type' => 2,
                'target' => 3,
                'size' => 7,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 10,
                'title' => 'Students brainstorm on their findings, and converge on one best/feasible solution. ',
                'time' => 30,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 11,
                'title' => "Students work out a plan/draw sketch design to construct prototype",
                'time' => 15,
                'type' => 3,
                'class_type' => 1,
                'target' => 1,
                'size' => 4,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 12,
                'title' => "Students receive feedback and comments from teachers and other students",
                'time' => 5,
                'type' =>6,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 13,
                'title' => "Students revise the design problem based on the feedback received.",
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 14,
                'title' => "Group discussion to identify the factors to be evaluate the prototype that fulfills users' need",
                'time' => 10,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 15,
                'title' => "Students list criteria/rubric used to evaluate the effectiveness of the prototype",
                'time' => 10,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 16,
                'title' => "Students explores the materials",
                'time' => 60,
                'type' => 8,
                'class_type' => 2,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 17,
                'title' => "Students produce an early, inexpensive, and scaled down version of the product ",
                'time' => 60,
                'type' => 12,
                'class_type' => 2,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 18,
                'title' => "Students receive teachers' instruction on the success criteria of the competition",
                'time' => 5,
                'type' => 1,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 19,
                'title' => "Students perform their product",
                'time' => 30,
                'type' => 8,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 20,
                'title' => "Students self/peer evaluate the performance of their products based on the rubrics.",
                'time' => 10,
                'type' => 6,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 21,
                'title' => "Students receive teachers' instruction on conducting a client interview for the effectiveness of the product.",
                'time' => 5,
                'type' => 1,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 22,
                'title' => "Students conduct a client interview to collect the feedback from the users who try out the products",
                'time' => 15,
                'type' => 8,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 23,
                'title' => "Students self/peer evaluate the performance of their products based on the rubrics.",
                'time' => 10,
                'type' => 6,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 24,
                'title' => "Students analyze the feedback from users/teachers, and search methods to optimie the product",
                'time' => 30,
                'type' => 5,
                'class_type' => 2,
                'target' => 3,
                'size' => 7,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 25,
                'title' => "Students brainstorm on their findings, and converge on one best/feasible solution. ",
                'time' => 10,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 26,
                'title' => "Students work out a plan/draw sketch design to construct prototype",
                'time' => 15,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 27,
                'title' => "Students work on the product optimization",
                'time' => 30,
                'type' => 7,
                'class_type' => 2,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 28,
                'title' => "Students observe the scenario of the design problem through stimulus",
                'time' => 5,
                'type' => 1,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 29,
                'title' => "Based on the scenario, students predict what would happen when a particular variable change.",
                'time' => 5,
                'type' => 9,
                'class_type' => 1,
                'target' => 3,
                'size' => 7,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 30,
                'title' => "Students discuss and explain what has been observed: whether and why.",
                'time' => 5,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 31,
                'title' => "Students write down the inquiry questions and shared with the whole class",
                'time' => 5,
                'type' => 3,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 32,
                'title' => "Students search and explore new relevant information about the variables of the problem",
                'time' => 30,
                'type' => 5,
                'class_type' => 2,
                'target' =>3,
                'size' => 7,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 33,
                'title' => "Group discussion and come up with some hypothesis",
                'time' => 10,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 34,
                'title' => "Write down the hypothesis and share with the whole class",
                'time' => 5,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 4,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 35,
                'title' => "Students receive feedback and comments from teachers and other students",
                'time' => 5,
                'type' => 6,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 36,
                'title' => "Students revise the hypothesis based on the feedback received.",
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 37,
                'title' => "Group discussion to differentiate dependent/independent/control varibles and design instrument to measure the variables",
                'time' => 15,
                'type' => 1,
                'class_type' => 1,
                'target' => 2,
                'size' => 4,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 38,
                'title' => "Students write a plan of scientific inquiry",
                'time' => 15,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 4,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 39,
                'title' => "Students reflect on the alignmennt between hypothesis and inquiry methods, as well as other practical issues of the experiment design",
                'time' => 5,
                'type' => 9,
                'class_type' => 1,
                'target' => 3,
                'size' => 7,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 40,
                'title' => "Students revise and finalize the plan",
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 41,
                'title' => "Group discussion to identify the factors to be monitored for the successful implementation of the experiment plan",
                'time' => 10,
                'type' => 2,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 42,
                'title' => "List criteria/rubric used to evaluate the success of the experiment ",
                'time' => 10,
                'type' => 3,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 43,
                'title' => "Conduct the experiment, observe the phenomena and record the data",
                'time' => 20,
                'type' => 12,
                'class_type' => 1,
                'target' => 2,
                'size' => 4,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 44,
                'title' => "Conduct self-/peer-assessment on the experiment procedure to identify the areas of improvement",
                'time' => 10,
                'type' => 6,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 45,
                'title' => "Improve the experienment design and operation",
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 46,
                'title' => "Summarize and display the data in the form of spreadsheets, tables, or charts.",
                'time' => 11,
                'type' => 9,
                'class_type' => 1,
                'target' => 2,
                'size' => 2,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 47,
                'title' => "Students identify causal and correlational relationship of different groups of data sets.",
                'time' => 5,
                'type' => 9,
                'class_type' => 1,
                'target' => 3,
                'size' => 7,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 48,
                'title' => "Students choose valid and reliable evidences that support the claims",
                'time' => 5,
                'type' => 9,
                'class_type' => 1,
                'target' => 3,
                'size' => 7,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 49,
                'title' => "Students apply scientific principles/theories to construct an explanation for the results.",
                'time' => 5,
                'type' => 9,
                'class_type' => 1,
                'target' => 3,
                'size' => 7,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 50,
                'title' => "Students write down their statements on the process of scientific reasoning",
                'time' => 5,
                'type' => 3,
                'class_type' => 1,
                'target' => 3,
                'size' => 7,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 51,
                'title' => "Conduct self-assessment on the scientific reasoning process (claim, evidence, reasoning )",
                'time' => 10,
                'type' => 6,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 52,
                'title' => "Students improve the process of scientific reasoning",
                'time' => 10,
                'type' => 7,
                'class_type' => 1,
                'target' => 2,
                'size' => 3,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 53,
                'title' => "Students construct graphical displays to illustrate the relationships of the variables, and present to the whole class",
                'time' => 10,
                'type' => 10,
                'class_type' => 1,
                'target' => 1,
                'size' => 1,
                'description' => '',
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);

        Schema::create('learningtask_template_assessment', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('learningtask_id');
            $table->unsignedBigInteger('learningoutcome_id');
            $table->smallInteger('created_by');
            $table->smallInteger('updated_by');
            $table->boolean('is_deleted');
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
            
            $table->foreign('learningtask_id')->references('id')->on('learningtask_template');
            $table->foreign('learningoutcome_id')->references('id')->on('learningtask_template');
        });

        // DB::table('learningtask_template_assessment')->insert([
        //     [
        //         'id' => 1,
        //         'learningtask_id' => '',
        //         'learningoutcome_id' => '',
        //         'created_by' => 1,
        //         'updated_by' => 1,
        //         'is_deleted' => 0,
        //     ]
        // ]);

        Schema::create('learningtask_template_resource', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('learningtask_id');
            $table->unsignedBigInteger('resource_id');
            $table->smallInteger('created_by');
            $table->smallInteger('updated_by');
            $table->boolean('is_deleted');
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();

            $table->foreign('learningtask_id')->references('id')->on('learningtask_template');
            $table->foreign('resource_id')->references('id')->on('resourceOpts');
        });

        DB::table('learningtask_template_resource')->insert([
            [
                'id' => 1,
                'learningtask_id' => 1,
                'resource_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 2,
                'learningtask_id' => 2,
                'resource_id' => 8,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 3,
                'learningtask_id' => 3,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 6,
                'learningtask_id' => 6,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 7,
                'learningtask_id' => 7,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 8,
                'learningtask_id' => 9,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 9,
                'learningtask_id' => 11,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 10,
                'learningtask_id' => 12,
                'resource_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 11,
                'learningtask_id' => 14,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 12,
                'learningtask_id' => 15,
                'resource_id' => 5,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 13,
                'learningtask_id' => 20,
                'resource_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 14,
                'learningtask_id' => 21,
                'resource_id' => 8,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 15,
                'learningtask_id' => 22,
                'resource_id' => 8,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 16,
                'learningtask_id' => 23,
                'resource_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 17,
                'learningtask_id' => 26,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 18,
                'learningtask_id' => 28,
                'resource_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 19,
                'learningtask_id' => 31,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 20,
                'learningtask_id' => 32,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 21,
                'learningtask_id' => 34,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 22,
                'learningtask_id' => 35,
                'resource_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 23,
                'learningtask_id' => 37,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 24,
                'learningtask_id' => 38,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 25,
                'learningtask_id' => 41,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 26,
                'learningtask_id' => 42,
                'resource_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 27,
                'learningtask_id' => 43,
                'resource_id' => 5,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 28,
                'learningtask_id' => 44,
                'resource_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 29,
                'learningtask_id' => 51,
                'resource_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
        ]);

        Schema::create('learningtask_template_etool', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('learningtask_id');
            $table->unsignedBigInteger('elearningtool_id');
            $table->smallInteger('created_by');
            $table->smallInteger('updated_by');
            $table->boolean('is_deleted');
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();

            $table->foreign('learningtask_id')->references('id')->on('learningtask_template');
            $table->foreign('elearningtool_id')->references('id')->on('resourceOpts');
        });

        DB::table('learningtask_template_etool')->insert([
            [
                'id' => 1,
                'learningtask_id' => 1,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 2,
                'learningtask_id' => 2,
                'elearningtool_id' => 5,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 3,
                'learningtask_id' => 2,
                'elearningtool_id' => 6,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 4,
                'learningtask_id' => 3,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 5,
                'learningtask_id' => 4,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 6,
                'learningtask_id' => 4,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 7,
                'learningtask_id' => 4,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 8,
                'learningtask_id' => 5,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 9,
                'learningtask_id' => 6,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 10,
                'learningtask_id' => 7,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 11,
                'learningtask_id' => 7,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 12,
                'learningtask_id' => 7,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 13,
                'learningtask_id' => 8,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 14,
                'learningtask_id' => 8,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 15,
                'learningtask_id' => 8,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 16,
                'learningtask_id' => 8,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 17,
                'learningtask_id' => 9,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 18,
                'learningtask_id' => 9,
                'elearningtool_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 19,
                'learningtask_id' => 11,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 20,
                'learningtask_id' => 11,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 21,
                'learningtask_id' => 11,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 22,
                'learningtask_id' => 12,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 23,
                'learningtask_id' => 13,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 24,
                'learningtask_id' => 15,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 25,
                'learningtask_id' => 20,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 26,
                'learningtask_id' => 21,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 27,
                'learningtask_id' => 22,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 28,
                'learningtask_id' => 22,
                'elearningtool_id' => 6,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 29,
                'learningtask_id' => 23,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 30,
                'learningtask_id' => 24,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 31,
                'learningtask_id' => 24,
                'elearningtool_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 32,
                'learningtask_id' => 26,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 33,
                'learningtask_id' => 26,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 34,
                'learningtask_id' => 28,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 35,
                'learningtask_id' => 30,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 36,
                'learningtask_id' => 31,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 37,
                'learningtask_id' => 32,
                'elearningtool_id' => 3,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 38,
                'learningtask_id' => 32,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 39,
                'learningtask_id' => 33,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 40,
                'learningtask_id' => 34,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 41,
                'learningtask_id' => 34,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 42,
                'learningtask_id' => 34,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 43,
                'learningtask_id' => 35,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 44,
                'learningtask_id' => 36,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 45,
                'learningtask_id' => 37,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 46,
                'learningtask_id' => 38,
                'elearningtool_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 47,
                'learningtask_id' => 38,
                'elearningtool_id' => 2,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 48,
                'learningtask_id' => 38,
                'elearningtool_id' => 7,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 49,
                'learningtask_id' => 42,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 50,
                'learningtask_id' => 44,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 51,
                'learningtask_id' => 46,
                'elearningtool_id' => 8,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 52,
                'learningtask_id' => 50,
                'elearningtool_id' => 8,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
            [
                'id' => 53,
                'learningtask_id' => 51,
                'elearningtool_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
                'is_deleted' => 0,
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('learningtask_template_assessment');
        Schema::dropIfExists('learningtask_template_resource');
        Schema::dropIfExists('learningtask_template_etool');
        Schema::dropIfExists('learningtask_template');
    }
}
